name: Docker Image Build Amd Push

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    # - name: Create .env file
    #   run: |
    #     echo VARIABLE=${{ secrets.ENV_VARIABLE }} >> .env
    #   # 可加入多個環境變數

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/github_action_test:latest  # 使用你的 Docker Hub 使用者名稱和應用程式名稱

    - name: 更新 known_hosts 文件  # 步驟的名稱
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.HOST_NAME }} >> ~/.ssh/known_hosts

    # - name: Create directory if not exists # 確保資料夾是存在的
    #   run: ssh ${{ secrets.DEPLOY_SSH_KEY }} ubuntu@${{ secrets.HOST_NAME }} "mkdir -p ~/websample/node-env/"

    # - name: Transfer .env file # 上傳環境變數
    #   run: scp .env root@${{ secrets.HOST_NAME }}:~/websample/node-env/

    - name: Deploy to Docker
      run: |
        ssh ubuntu@${{ secrets.HOST_NAME }} '
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/github_action_test:latest
          docker rm -f github_action_test || true
          docker run -d -p 3003:3000 --name github_action_test ${{ secrets.DOCKER_HUB_USERNAME }}/github_action_test:latest
        '
      # Docker 指令中，不能使用 `~` 路徑，可以使用 $Home 作為替代
