name: Docker Image Build Amd Push

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18
        
    - name: npm install, build and test
      run: |
        npm install
      
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    # - name: Create .env file
    #   run: |
    #     echo VARIABLE=${{ secrets.ENV_VARIABLE }} >> .env
    #   # 可加入多個環境變數

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/github_action_test:latest  # 使用你的 Docker Hub 使用者名稱和應用程式名稱

    # - name: Create directory if not exists # 確保資料夾是存在的
    #   run: ssh ${{ secrets.DEPLOY_SSH_KEY }} ubuntu@${{ secrets.HOST_NAME }} "mkdir -p ~/websample/node-env/"

    # - name: Transfer .env file # 上傳環境變數
    #   run: scp .env root@${{ secrets.HOST_NAME }}:~/websample/node-env/

    - name: Deploy to Docker
      run: |
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.HOST_NAME }} '
          sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/github_action_test:latest
          sudo docker stop github_action_test 
          sudo docker run -d  --rm --name github_action_test -p 3003:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/github_action_test:latest
        '
      # Docker 指令中，不能使用 `~` 路徑，可以使用 $Home 作為替代
