name: Docker Image Build and Deploy

on:
  push:
    branches: ["main"]

env:
  DEPLOY_SSH_USER: Monday
  DEPLOY_SSH_IP: 54.199.96.160

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_PROJECT }}:latest

      - name: Deploy to Docker
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ env.DEPLOY_SSH_USER }}@${{ env.DEPLOY_SSH_IP }} '
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_PROJECT }}:latest
            sudo docker stop ${{ secrets.DOCKER_HUB_PROJECT }}
            sudo docker run -d  --rm --name ${{ secrets.DOCKER_HUB_PROJECT }} -p 8080:80 ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_PROJECT }}:latest
          '
